import StaticPageShell, {
  staticBodyStyle,
  staticCardStyle,
  staticSectionTitleStyle,
  staticSectionWrapperStyle,
} from "../../components/StaticPageShell";

export default function TermsPage() {
  return (
    <StaticPageShell
      pill="TERMS"
      title="Conditions of use for VIREKA Space"
      intro="These Terms govern the use of the service and clarify its role, limits, and user responsibility."
    >
      <section style={staticSectionWrapperStyle}>
        <div style={staticCardStyle}>
          <h2 style={staticSectionTitleStyle}>Introduction</h2>
          <p style={staticBodyStyle}>
            These Terms govern the use of VIREKA Space.
            <br />
            <br />
            VIREKA Space provides a structured environment for clarifying how
            situations are being understood before decisions are made or AI prompts
            are written. By accessing or using the service, you agree to these
            Terms. If you do not agree, please do not use the service.
            <br />
            <br />
            These Terms are intended to establish clarity regarding the nature of
            the service, appropriate use, and the responsibilities of both the user
            and the service provider.
          </p>
        </div>
      </section>

      <section style={staticSectionWrapperStyle}>
        <div style={staticCardStyle}>
          <h2 style={staticSectionTitleStyle}>Use of the service</h2>
          <p style={staticBodyStyle}>
            VIREKA Space may be used to explore how situations are interpreted,
            including identifying what appears to be happening, what may be assumed,
            and what may remain unclear.
            <br />
            <br />
            The service is provided for informational and interpretive support
            purposes only.
            <br />
            <br />
            Use of the service does not create a professional relationship of any
            kind.
          </p>
        </div>
      </section>

      <section style={staticSectionWrapperStyle}>
        <div style={staticCardStyle}>
          <h2 style={staticSectionTitleStyle}>Nature of the service</h2>
          <p style={staticBodyStyle}>
            VIREKA Space does not provide medical, legal, financial, therapeutic, or
            emergency advice.
            <br />
            <br />
            The service does not guarantee correctness, completeness, or suitability
            for any particular purpose.
            <br />
            <br />
            Users remain responsible for their own interpretations, decisions, and
            actions.
          </p>
        </div>
      </section>

      <section style={staticSectionWrapperStyle}>
        <div style={staticCardStyle}>
          <h2 style={staticSectionTitleStyle}>User responsibility</h2>
          <p style={staticBodyStyle}>
            Users agree to use the service lawfully and responsibly.
            <br />
            <br />
            Users should not rely on the service as a substitute for professional
            judgment, especially in situations involving risk, safety, health,
            legality, or significant consequences.
            <br />
            <br />
            Users are responsible for the content they submit and for how they use
            any output generated by the service.
          </p>
        </div>
      </section>

      <section style={staticSectionWrapperStyle}>
        <div style={staticCardStyle}>
          <h2 style={staticSectionTitleStyle}>Availability and changes</h2>
          <p style={staticBodyStyle}>
            The service may change, be updated, interrupted, or discontinued at any
            time.
            <br />
            <br />
            Features, limits, and access conditions may evolve as the system
            develops.
            <br />
            <br />
            VIREKA Space is not liable for temporary unavailability or for changes
            to functionality.
          </p>
        </div>
      </section>

      <section style={staticSectionWrapperStyle}>
        <div style={staticCardStyle}>
          <h2 style={staticSectionTitleStyle}>Limitation of liability</h2>
          <p style={staticBodyStyle}>
            To the fullest extent permitted by law, VIREKA Space is provided “as is”
            and without warranties of any kind.
            <br />
            <br />
            The service provider is not liable for any direct, indirect, incidental,
            consequential, or reliance-based loss arising from use of the service.
          </p>
        </div>
      </section>

      <section style={staticSectionWrapperStyle}>
        <div style={staticCardStyle}>
          <h2 style={staticSectionTitleStyle}>Updates to these Terms</h2>
          <p style={staticBodyStyle}>
            These Terms may be updated periodically to reflect changes in the
            service, legal requirements, or operating practices.
            <br />
            <br />
            Continued use of the service after updates constitutes acceptance of the
            revised Terms.
          </p>
        </div>
      </section>
    </StaticPageShell>
  );
}
